version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-enabled
    depends_on:
      - django
    networks:
      - webnet

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=strenghtbarathlete.settings
    networks:
      - webnet

networks:
  webnet:
