# Generated by Django 5.0.2 on 2024-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('banner_photo', models.ImageField(upload_to='event_photos/')),
                ('heading_photo', models.ImageField(upload_to='event_photos/')),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in hours')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_title', models.CharField(max_length=200)),
                ('youtube_video_url', models.ManyToManyField(blank=True, related_name='event_links', to='app.mediaurls')),
                ('other_photos', models.ManyToManyField(related_name='event_photos', to='app.photos')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner_photo', models.ImageField(upload_to='event_photos/')),
                ('heading_photo', models.ImageField(upload_to='event_photos/')),
                ('description', models.TextField()),
                ('other_photos', models.ManyToManyField(related_name='program_photos', to='app.photos')),
                ('youtube_video_url', models.ManyToManyField(blank=True, related_name='programs_links', to='app.mediaurls')),
            ],
        ),
    ]
