# Generated by Django 5.0.2 on 2024-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='heading_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
