# Generated by Django 5.0.2 on 2024-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_program_heading_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
