# Generated by Django 5.0.2 on 2024-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_youtubeurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='other_photos',
            field=models.ManyToManyField(null=True, related_name='event_photos', to='app.photos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_video_url',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_links', to='app.mediaurls'),
        ),
        migrations.AlterField(
            model_name='program',
            name='other_photos',
            field=models.ManyToManyField(null=True, related_name='program_photos', to='app.photos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='youtube_video_url',
            field=models.ManyToManyField(blank=True, null=True, related_name='programs_links', to='app.mediaurls'),
        ),
    ]
