# Generated by Django 5.0.2 on 2024-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_other_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='other_photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_photos', to='app.photos'),
        ),
        migrations.AlterField(
            model_name='program',
            name='other_photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='program_photos', to='app.photos'),
        ),
    ]
