# Generated by Django 5.0.2 on 2024-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(help_text='Duration in hours', max_length=100),
        ),
    ]
